# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Check Doc Links

# This workflow checks all links from Airflow doc via Lychee: https://github.com/lycheeverse/lychee
# The check is done directly from website in case build process creates / transforms links
# It has a schedule to run at least once a day in order to detect dangling external links in case there
# is no activity on this repo itself.

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 7 * * *"

jobs:

  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: 'https://airflow.apache.org/docs/'

      - name: Output stats
        run: |
              echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
              echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
              echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          output: 'lychee.md'
          args: 'https://airflow.apache.org/docs/'
